### ISSUE TITLE
Is the plugin maintained?

### ISSUE THREAD

**Issue by timsk-ru** [salar90/wp-api-stats#4]
Hi,

Testing this plugin with Wordpress 5.4.2 on PHP 7.3 all appears to work correctly with no errors. If the code is still checked and maintained against current Wordpress, may be worth updating the compatibility statements on wordpress.org to avoid people dropping it due to compatibility warnings.

Useful and fills a gap that only seems to be filled otherwise via raw access.log analysis.

Timsk

**Comment by salar90** [comment]
Hi Timsk,
Thank you for testing and your recommendation.
I tested against WordPress 5.5.1 and updated the compatibility statements on wordpress.org.

Also,  I would appreciate any ideas or recommendation about plugin itself.

Many thanks
